create_clock -name clock -period 100 [get_ports {clock}]
set_input_delay  -max 1 -clock clock [get_ports {reset}]
set_input_delay  -min 1 -clock clock [get_ports {reset}]
set_output_delay -max 1 -clock clock [get_ports {stop}]
set_output_delay -min 1 -clock clock [get_ports {stop}]
set_input_delay -max 1 -clock clock [get_ports main_k_163]
set_input_delay -min 1 -clock clock [get_ports main_k_163]
