# Test 2025-07-27 at 18:29:59

name: Test
run-name: btreeAsm

on:
  push:
    paths:
      - '**/main.yml'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:

  test:
    permissions: write-all
    runs-on: ubuntu-latest

    strategy:
      matrix:
        task: [Verilog]

    steps:
    - uses: actions/checkout@v4
      with:
        ref: 'main'

    - name: 'JDK 24'
      uses: oracle-actions/setup-java@v1
      with:
        website: jdk.java.net

    - name: Verilog install
      run: |
        sudo apt install iverilog

    - name: Position files in package
      run: |
        mkdir -p com/AppaApps/Silicon
        cp *.java com/AppaApps/Silicon

    - name: Java
      run: |
        javac -g -d Classes -cp Classes com/AppaApps/Silicon/*.java

    - name: Test Verilog
      if: matrix.task == 'Verilog'
      run: |
        java -cp Classes com/AppaApps/Silicon/Verilog

