# Test 2025-08-23 at 05:05:31

name: Test
run-name: btreeAsm

on:
  push:
    paths:
      - '**/main.yml'

#concurrency:
#  group: ${{ github.workflow }}-${{ github.ref }}
# cancel-in-progress: true

jobs:

  test:
    permissions: write-all
    runs-on: ubuntu-latest

    strategy:
      matrix:
        task: [Btree, Children, Chip, Test, Verilog]

    steps:
    - uses: actions/checkout@v4
      with:
        ref: 'main'

    - name: 'JDK 24'
      uses: oracle-actions/setup-java@v1
      with:
        website: jdk.java.net

    - name: Verilog install
      run: |
        sudo apt install iverilog yosys

    - name: Position files in package
      run: |
        mkdir -p com/AppaApps/Silicon
        cp *.java com/AppaApps/Silicon

    - name: Java
      run: |
        javac -g -d Classes -cp Classes com/AppaApps/Silicon/*.java

    - name: Test Btree
      if: matrix.task == 'Btree'
      run: |
        java -cp Classes com/AppaApps/Silicon/Btree


    - name: Test Children
      if: matrix.task == 'Children'
      run: |
        java -cp Classes com/AppaApps/Silicon/Children


    - name: Test Chip
      if: matrix.task == 'Chip'
      run: |
        java -cp Classes com/AppaApps/Silicon/Chip


    - name: Test Test
      if: matrix.task == 'Test'
      run: |
        java -cp Classes com/AppaApps/Silicon/Test


    - name: Test Verilog
      if: matrix.task == 'Verilog'
      run: |
        java -cp Classes com/AppaApps/Silicon/Verilog

